import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import Navbar from './Navbar'
import Banner from './Banner'
import About from './About'
import Service from './Service'
import Project from './Project'
import Contact from './Contact'
import Footer from './Footer'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Advertise-Multi Page Nextjs Protfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
        {/* Bootstrap v5 css cdn */}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
      </Head>
        {/* Bootstrap v5 js cdn */}
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script>
      <main className={styles.main}>
       <Navbar/>
      <Banner/>
      <About/>
      <Service/>
      <Project/>
      <Contact/>
      <Footer/>
        </main>
    </div>
  )
}
